# conan-profiles/clang-cl-windows-release.ini
[settings]
arch=x86_64
os=Windows
build_type=Release
compiler=clang
compiler.version=17
compiler.cppstd=23
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.runtime_version=v143

[conf]
tools.build:compiler_executables={"c":"clang-cl","cpp":"clang-cl"}
tools.cmake.cmaketoolchain:generator=Ninja
